### ISSUE TITLE
[bug] Clicking below the dropdown also hides the top menu

### ISSUE THREAD

**Issue by Knochenmark** [PenguinOfTheSky/AuthorPal#16]
The container of the toggle button also hides top menu, so it can happen, that when you miss the dropdown menu and click below it, that the topmenu will be toggled to hidden. Should be a simple fix by moving the click handler to the button instead of its container.

**Comment by Knochenmark** [comment]
#18

**Comment by PenguinOfTheSky** [comment]
Merged & solved.
