### ISSUE TITLE
[enhancement] Show a list of projects you have in storage on homescreen for direct loading

### ISSUE THREAD

**Issue by Knochenmark** [PenguinOfTheSky/AuthorPal#19]
You obviously have some information about the projects that are already stored and can be loaded/opened. Use this list to show a list in the main/home screen and load the project when clicking on the name. Kinda like a quick selection so you can jump right back into the project you worked on last time or even jump between a few projects more quickly.

**Comment by PenguinOfTheSky** [comment]
Hmm, not entirely sure how to implement a quick-switch between projects (though may have an idea for opening multiple projects.
List of projects on splash screen is easy enough though. live with v2.1.0

**Comment by Knochenmark** [comment]
i think you can close this one, for the quick switch you would just need a way to get back to the home screen to load another project then.

**Comment by PenguinOfTheSky** [comment]
yeppers, that part's coming in 2.3 I think.
